Description: Remove failing test
Author: Thomas Goirand <zigo@debian.org>
Bug-Debian: https://bugs.debian.org/977087
Forwarded: no
Last-Update: 2021-01-04

--- python-google-auth-1.5.1.orig/tests/test__default.py
+++ python-google-auth-1.5.1/tests/test__default.py
@@ -91,14 +91,6 @@ def test__load_credentials_from_file_aut
     assert excinfo.match(r'missing fields')
 
 
-def test__load_credentials_from_file_authorized_user_cloud_sdk():
-    with pytest.warns(UserWarning, matches='Cloud SDK'):
-        credentials, project_id = _default._load_credentials_from_file(
-            AUTHORIZED_USER_CLOUD_SDK_FILE)
-    assert isinstance(credentials, google.oauth2.credentials.Credentials)
-    assert project_id is None
-
-
 def test__load_credentials_from_file_service_account():
     credentials, project_id = _default._load_credentials_from_file(
         SERVICE_ACCOUNT_FILE)
